<%-- 
    Document   : sales
    Created on : Dec 8, 2019, 3:12:25 PM
    Author     : Brian
--%>

<%@ page language="java" contentType="text/html; charset=ISO-8859-1"
	pageEncoding="ISO-8859-1"%>
<%@ page import="java.sql.*"%>
<%@ page import="javax.servlet.http.*,javax.servlet.*"%>
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>Sales Reports</title>
    </head>
    <body>
        <h1>Sales Reports</h1>
        <%
            if(session.getAttribute("user") == null){
        %>        
                You are not logged in<br/>
                <a href="login.jsp">Please Login</a>
        <%
            }else if(!session.getAttribute("security_level").equals("admin")){
        %>        
                    You do not have permission to view this page.
                    <br/>
                    <a href="home.jsp">Return to Home</a>

        <%
            }else{
        %>
                <a href='logout.jsp'>Log out</a> -- <a href='home.jsp'>Return to Home</a>
        <%
                //Get the values submitted in the form
                String reportType = request.getParameter("type");
                String year_month = request.getParameter("reportMonth");
                String month = "", year = "";
                if(year_month != null){
                    month = year_month.split("-")[1];
                    year = year_month.split("-")[0];
                }
                String lineid = request.getParameter("lineid");
                String flightnum = request.getParameter("flightnum");
                String custid = request.getParameter("custid");

                //Make sure the JDBC driver is properly loaded
                Class.forName("com.mysql.jdbc.Driver");
                //Connect to the database
                Connection con = DriverManager.getConnection("jdbc:mysql://cs336-group32.cbuttaegl5pc.us-east-1.rds.amazonaws.com:3306/FlightSystem","admin", "adminadmin");
                Statement st = con.createStatement();
                ResultSet rs;

                if(reportType.equals("maxcust")){
                    rs = st.executeQuery("SELECT spent.username, p.name, spent.total_spent "
                            + "FROM (SELECT username, SUM(total_fare) total_spent "
                                + "FROM Customer "
                                + "JOIN Ticket USING (username) "
                                + "GROUP BY username) spent "
                            + "JOIN Person p USING (username) "
                            + "WHERE spent.total_spent = "
                            + "(SELECT MAX(spent.total_spent) FROM "
                                    + "(SELECT username, SUM(total_fare) total_spent "
                                    + "FROM Customer "
                            + "JOIN Ticket USING (username) "
                            + "GROUP BY username) spent);");
                    if(rs.next()){
        %>
                        <p>The Maximum Spending Customer is <%=rs.getString("name")%> (<%=rs.getString("username")%>) who spent $<%=rs.getString("total_spent")%></p>
        <%   
                    }else{
                        out.println("Error: Could not find maximum spending customer!");
                        out.println("<a href='home.jsp'>Return to Home</a>");
                    }
                } else if(reportType.equals("month")){
                    rs = st.executeQuery("SELECT SUM(total_fare) revenue FROM Ticket WHERE MONTH(issue_date) = " + month + " AND YEAR(issue_date) = " + year + ";");
                    if(rs.next()){
        %>
                        <p>The total revenue for <%=month+"/"+year%> was $<%=rs.getString("revenue")%></p>
        <%
                    }else{
                        out.println("Error: Could not get a sales report for the given month!");
                        out.println("<a href='home.jsp'>Return to Home</a>");
                    }
                }else if(reportType.equals("airline")){
                    rs = st.executeQuery("SELECT tr.lid, SUM(ti.total_fare) revenue FROM Ticket ti "
                        + "JOIN Trip tr USING (tnumber) "
                        + "WHERE tr.lid = '" + lineid + "' "
                        + "GROUP BY tr.lid;");
                    if(rs.next()){
        %>
                        <p>The total revenue generated by <%=lineid%> Airline is $<%=rs.getString("revenue")%></p>
        <%
                    }else{
        %>
                        <p>The total revenue generated by <%=lineid%> Airline is $0</p>
        <%
                    }
                }else if(reportType.equals("flight")){
                    rs = st.executeQuery("SELECT tr.lid, tr.number, SUM(ti.total_fare) revenue FROM Ticket ti "
                        + "JOIN Trip tr USING (tnumber) "
                        + "WHERE tr.lid = '" + lineid + "' AND tr.number = '" + flightnum + "' "
                        + "GROUP BY tr.lid, tr.number;");
                    if(rs.next()){
        %>
                        <p>The total revenue generated by Flight <%=flightnum%> at <%=lineid%> Airline is $<%=rs.getString("revenue")%></p>
        <%
                    }else{
        %>
                        <p>The total revenue generated by Flight <%=flightnum%> at <%=lineid%> Airline is $0</p>
        <%
                    }
                }else if(reportType.equals("cust")){
                    rs = st.executeQuery("SELECT p.username, p.name, SUM(ti.total_fare) total_spent "
                        + "FROM Customer c "
                        + "JOIN Ticket ti USING (username) "
                        + "JOIN Person p USING (username) "
                        + "WHERE c.username = '"+ custid +"' "
                        + "GROUP BY c.username;");
                    if(rs.next()){
        %>
                        <p>Customer <%=rs.getString("name")%> (<%=rs.getString("username")%>) spent a total of $<%=rs.getString("total_spent")%></p>
        <%
                    }else{
        %>
                        <p>User <%=custid%> has either not made any purchases or is not a customer</p>
        <%
                    }
                }
            }
        %>
        <br/><div style="border:1px solid black; padding:10px;">
            <p><b>Get Different Sales Information</b></p>
            <form action="sales.jsp" method="POST">
                <input type="hidden" name="type" value="month"/>
                <u>Monthly Sales Report</u><br/>
                Month: <input type="month" name="reportMonth"/>
                <input type="submit" value="Submit"/>
            </form><br/>
            <form action="sales.jsp" method="POST">
                <input type="hidden" name="type" value="airline"/>
                <u>Sales For Airline</u><br/>
                Airline ID: <input type="text" name="lineid" maxlength="2"/>
                <input type="submit" value="Submit"/>
            </form><br/>
            <form action="sales.jsp" method="POST">
                <input type="hidden" name="type" value="flight"/>
                <u>Sales For Flight</u><br/>
                Flight Airline: <input type="text" name="lineid" maxlength="2"/>
                Flight Number: <input type="number" name="flightnum"/>
                <input type="submit" value="Submit"/>
            </form><br/>
            <form action="sales.jsp" method="POST">
                <input type="hidden" name="type" value="cust"/>
                <u>Sales For Customer</u><br/>
                Customer Username: <input type="text" name="custid"/>
                <input type="submit" value="Submit"/>
            </form><br/>
            <form action="sales.jsp" method="POST">
                <input type="hidden" name="type" value="maxcust"/>
                <u>Sales for the Maximum Spending Customer:</u>
                <input type="submit" value="Go"/>
            </form>
        </div>
    </body>
</html>
